version: '3.9'
services:
  ganache:
    image: branxz07/digitalidentityimage:latest
    container_name: ganache
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.2
    ports:
      - "8546:8546"
    volumes:
      - ./ganache:/tokPhyApp/ganache
    command: >
      bash -c "
        cd /tokPhyApp/ganache &&
        npm install -g ganache-cli &&
        npm update &&
        chmod 544 startApp &&
      "

  apigateway:
    image: branxz07/digitalidentityimage:latest
    container_name: apigateway
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.3
    ports:
      - "5500:5500"
      - "9876:9876"
    volumes:
      - ./apigateway:/apigateway
    command: >
      bash -c "
        cd /apigateway/apigatewayApp &&
        npm update &&
        chmod 544 startApp &&
      "
  birthcertificate:
    image: branxz07/digitalidentityimage:latest
    container_name: birthcertificate
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.4
    ports:
      - "5501:5501"
    volumes:
      - ./birthCertificate:/birthcertificate
    command: >
      bash -c "
        cd /birthcertificate/birthCertificateApp &&
        npm update &&
        chmod 544 startApp &&
      "

  digitalidentity:
    image: branxz07/digitalidentityimage:latest
    container_name: digitalidentity
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.5
    ports:
      - "5502:5502"
    volumes:
      - ./digitalIdentity:/digitalidentity
    command: >
      bash -c "
        cd /digitaldentity/digitaldentityApp &&
        npm update &&
        chmod 544 startApp &&
      "

  users:
    image: branxz07/digitalidentityimage:latest
    container_name: users
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.6
    ports:
      - "5503:5503"
    volumes:
      - ./users:/users
    command: >
      bash -c "
        cd /users/usersApp &&
        npm update &&
        chmod 544 startApp &&
      "

  scholarcurriculum:
    image: branxz07/digitalidentityimage:latest
    container_name: scholarcurriculum
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.7
    ports:
      - "5504:5504"
    volumes:
      - ./scholarCurriculum:/scholarcurriculum
    command: >
      bash -c "
        cd /scholarcurriculum/scholarCurriculumApp &&
        npm update &&
        chmod 544 startApp &&
      "

  frontendusersinterface:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendusersinterface
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.11
    ports:
      - "5512:5512"
    volumes:
      - ./frontendUsersInteface:/frontendusersinterface
    command: >
      bash -c "
        apt-get update &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        cd frontendusersinteface/frontendUsersApp/ &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
      "

  frontendbirthcertificate:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendbirthcertificate
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.12
    ports:
      - "5510:5510"
    volumes:
      - ./frontendBirthCertificate:/frontendbirthcertificate
    command: >
      bash -c "
        apt-get update &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        cd frontendbirthcertificate/frontendBirthCertificateApp/ &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
      "

  frontendidentitydigital:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendidentitydigital
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.13
    ports:
      - "5511:5511"
    volumes:
      - ./frontendIdentityDigital:/frontendidentitydigital
    command: >
      bash -c "
        apt-get update &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        cd frontendidentitydigital/frontendDigitalApp/ &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
      "

  frontendscholarcurriculum:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendscholarcurriculum
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.14
    ports:
      - "5513:5513"
    volumes:
      - ./frontendScholarCurriculum:/frontendscholarcurriculum
    command: >
      bash -c "
        apt-get update &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        cd frontendscholarcurriculum/frontendScholarCurriculumApp/ &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
      "

networks:
  TokPhyAppNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
