version: '3.9'
services:
  ganache:
    image: branxz07/digitalidentityimage:latest
    container_name: ganache
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.2
    ports:
      - "8546:8546"
    volumes:
      - ./ganache:/tokPhyApp/ganache
    command: >
      bash -c '
      cd /tokPhyApp/ganache &&
      if [ ! -f .setup_done ]; then
        npm install ganache --global &&
        npm update &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  apigateway:
    image: branxz07/digitalidentityimage:latest
    container_name: apigateway
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.3
    ports:
      - "5500:5500"
      - "9876:9876"
    volumes:
      - ./apigateway:/apigateway
    command: >
      bash -c '
      cd /apigateway/apigatewayApp &&
      if [ ! -f .setup_done ]; then
        npm update &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  birthcertificate:
    image: branxz07/digitalidentityimage:latest
    container_name: birthcertificate
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.4
    ports:
      - "5501:5501"
    volumes:
      - ./birthCertificate:/birthcertificate
    command: >
      bash -c '
      cd /birthcertificate/birthCertificateApp &&
      if [ ! -f .setup_done ]; then
        apt-get update -y &&
        npm update &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  digitalidentity:
    image: branxz07/digitalidentityimage:latest
    container_name: digitalidentity
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.5
    ports:
      - "5502:5502"
    volumes:
      - ./digitalIdentity:/digitalidentity
    command: >
      bash -c '
      cd /digitalidentity/digitaldentityApp &&
      if [ ! -f .setup_done ]; then
        npm update &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  users:
    image: branxz07/digitalidentityimage:latest
    container_name: users
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.6
    ports:
      - "5503:5503"
    volumes:
      - ./users:/users
    command: >
      bash -c '
      cd /users/usersApp &&
      if [ ! -f .setup_done ]; then
        npm update &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  scholarcurriculum:
    image: branxz07/digitalidentityimage:latest
    container_name: scholarcurriculum
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.7
    ports:
      - "5504:5504"
    volumes:
      - ./scholarCurriculum:/scholarcurriculum
    command: >
      bash -c '
      cd /scholarcurriculum/scholarCurriculumApp &&
      if [ ! -f .setup_done ]; then
        npm update &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  frontendusersinterface:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendusersinterface
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.11
    ports:
      - "5512:5512"
    volumes:
      - ./frontendUsersInteface:/frontendusersinterface
    command: >
      bash -c '
      cd /frontendusersinterface/frontendUsersApp/ &&
      if [ ! -f .setup_done ]; then
        apt-get update -y &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  frontendbirthcertificate:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendbirthcertificate
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.12
    ports:
      - "5510:5510"
    volumes:
      - ./frontendBirthCertificate:/frontendbirthcertificate
    command: >
      bash -c '
      cd /frontendbirthcertificate/frontendBirthCertificateApp/ &&
      if [ ! -f .setup_done ]; then
        apt-get update -y &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  frontendidentitydigital:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendidentitydigital
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.13
    ports:
      - "5511:5511"
    volumes:
      - ./frontendIdentityDigital:/frontendidentitydigital
    command: >
      bash -c '
      cd /frontendidentitydigital/frontendDigitalApp/ &&
      if [ ! -f .setup_done ]; then
        apt-get update -y &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

  frontendscholarcurriculum:
    image: branxz07/digitalidentityimage:latest
    container_name: frontendscholarcurriculum
    networks:
      TokPhyAppNetwork:
        ipv4_address: 172.18.1.14
    ports:
      - "5513:5513"
    volumes:
      - ./frontendScholarCurriculum:/frontendscholarcurriculum
    command: >
      bash -c '
      cd /frontendscholarcurriculum/frontendScholarCurriculumApp/ &&
      if [ ! -f .setup_done ]; then
        apt-get update -y &&
        apt-get upgrade -y &&
        apt-get install -y libcurl4-openssl-dev &&
        npm update &&
        npm install -g nodemon &&
        npm install axios dotenv bcrypt jsonwebtoken mysql2 &&
        chmod 544 startApp &&
        touch .setup_done
      fi &&
      tail -f /dev/null
      '

networks:
  TokPhyAppNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
