http:
  port: 5500
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'

  birthcertificateproof:
    host: localhost
    paths: '/proof'    

  birthcertificateproofB:
    host: '172.18.1.3'
    paths: '/proof'    

  birthcertificateCreate:
    host:  localhost
    paths: '/create' 

  birthcertificateCreateB:
    host:  '172.18.1.3'
    paths: '/create' 

  birthcertificateSetAddress:
    host:  localhost
    paths: '/setAddress' 

  birthcertificateSetAddressB:
    host:  '172.18.1.3'
    paths: '/setAddress' 

  birthcertificateConsult:
    host:  localhost
    paths: '/consult' 

  birthcertificateConsultB:
    host:  '172.18.1.3'
    paths: '/consult' 

  # digital identity services

  #Create
  didentityCreate:
    host:  localhost
    paths: '/createDigitalIdentity'    

  didentityCreateB:
    host:  '172.18.1.3'
    paths: '/createDigitalIdentity'        


  #LinkToken
  didentitylinkToken:
    host:  localhost
    paths: '/linkToken'    

  didentitylinkTokenB:
    host:  '172.18.1.3'
    paths: '/linkToken'       



  #Consult token name 
  didentityconsultTokens:
    host:  localhost
    paths: '/consultTokens'    

  didentityconsultTokensB:
    host:  '172.18.1.3'
    paths: '/consultTokens'       



  #consult token government
  didentityconsultTokenGovernment:
    host:  localhost
    paths: '/consultTokenGovernment'    

  didentityconsultTokenGovernmentB:
    host:  '172.18.1.3'
    paths: '/consultTokenGovernment'      



  #consult number of tokens
  didentityconsultNumberToken:
    host:  localhost
    paths: '/consultNumberToken'    

  didentityconsultNumberTokenB:
    host:  '172.18.1.3'
    paths: '/consultNumberToken'    

  #consult parameters of digital contructor
  didentityConsult:
    host:  localhost
    paths: '/consultDigitalIdentity'    

  didentityConsultB:
    host:  '172.18.1.3'
    paths: '/consultDigitalIdentity'  

  #proof method
  didentityProof:
    host:  localhost
    paths: '/proofd'    

  didentityProofB:
    host:  '172.18.1.3'
    paths: '/proofd'  




# users services

  #Create
  usersCreate:
    host:  localhost
    paths: '/createUser'    

  usersCreateB:
    host:  '172.18.1.3'
    paths: '/createUser'    

  #Consult
  usersConsult:
    host:  localhost
    paths: '/consultuser'    

  usersConsultB:
    host:  '172.18.1.3'
    paths: '/consultuser'  
  

  #Consult info
  usersGetInfo:
    host:  localhost
    paths: '/getInfoUser'    

  usersGetInfoB:
    host:  '172.18.1.3'
    paths: '/getInfoUser' 


  #RegisterUsers
  usersRegister:
    host:  localhost
    paths: '/registerUser'    

  usersRegisterB:
    host:  '172.18.1.3'
    paths: '/registerUser'  


  #Proof
  usersProof:
    host:  localhost
    paths: '/proofu'    

  usersProofB:
    host:  '172.18.1.3'
    paths: '/proofu'  




serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'

  users:
    url: 'http://172.18.1.6:5503'

  didentity:
    url: 'http://172.18.1.5:5502'

  birthcertificate:
    url: 'http://172.18.1.4:5501'   #this is the name of the host   

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  genesisPipeline:
    apiEndpoints:
      - birthcertificateproof
      - birthcertificateCreate
      - birthcertificateConsult
      - birthcertificateSetAddress
      - birthcertificateproofB
      - birthcertificateCreateB
      - birthcertificateConsultB
      - birthcertificateSetAddressB

    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: birthcertificate 
              changeOrigin: true

  didentityPipeline:
    apiEndpoints:      
      - didentityCreate   
      - didentityCreateB  
      - didentitylinkToken
      - didentitylinkTokenB  
      - didentityconsultTokens
      - didentityconsultTokensB
      - didentityconsultTokenGovernment
      - didentityconsultTokenGovernmentB
      - didentityconsultNumberToken
      - didentityconsultNumberTokenB
      - didentityConsult
      - didentityConsultB
      - didentityProof
      - didentityProofB
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: didentity 
              changeOrigin: true

  usersPipeline:
    apiEndpoints:      
      - usersCreate
      - usersCreateB
      - usersConsult
      - usersConsultB
      - usersGetInfo
      - usersGetInfoB
      - usersRegister
      - usersRegisterB
      - usersProof
      - usersProofB
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: users 
              changeOrigin: true

