http:
  port: 5500
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'

  genesisidentityproof:
    host: localhost
    paths: '/proof'    

  genesisidentityproofB:
    host: '172.18.1.3'
    paths: '/proof'    

  genesisidentityCreate:
    host:  localhost
    paths: '/create' 
    #methods: ["POST"]

  genesisidentityCreateB:
    host:  '172.18.1.3'
    paths: '/create' 
    #methods: ["POST"]

  genesisidentityConsult:
    host:  localhost
    paths: '/consult' 

  genesisidentityConsultB:
    host:  '172.18.1.3'
    paths: '/consult' 


  didentityConsultField:
    host:  d1c73e42f49e
    paths: '/consult/field'        

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'

  didentity:
    url: 'http://172.18.1.3:5502'

  genesisidentity:
    url: 'http://172.18.1.4:5501'   #this is the name of the host   

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  genesisPipeline:
    apiEndpoints:
      - genesisidentityproof
      - genesisidentityCreate
      - genesisidentityConsult
      - genesisidentityproofB
      - genesisidentityCreateB
      - genesisidentityConsultB

    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: genesisidentity 
              changeOrigin: true

  didentityPipeline:
    apiEndpoints:      
      - didentityConsultField      
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: didentity 
              changeOrigin: true

